import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const DEFAULT_CONFIG = path.join(ROOT, 'etl', 'config', 'clients.sample.json')

function parseArgs(argv) {
  const out = {
    env: 'dev',
    config: DEFAULT_CONFIG,
    out: '',
    sample: false,
  }

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    const next = () => String(argv[++i] || '')

    if (arg === '--env') out.env = next()
    else if (arg.startsWith('--env=')) out.env = arg.slice('--env='.length)
    else if (arg === '--config') out.config = next()
    else if (arg.startsWith('--config=')) out.config = arg.slice('--config='.length)
    else if (arg === '--out') out.out = next()
    else if (arg.startsWith('--out=')) out.out = arg.slice('--out='.length)
    else if (arg === '--sample') out.sample = true
    else if (arg === '--help' || arg === '-h') out.help = true
    else throw new Error(`Unknown argument: ${arg}`)
  }

  return out
}

function printHelp() {
  console.log(`Usage:
  node etl/scripts/collect_snapshot.mjs --env dev --sample
  node etl/scripts/collect_snapshot.mjs --env prod --config etl/config/clients.sample.json
`)
}

async function loadClients(filePath) {
  const text = await fs.readFile(filePath, 'utf8')
  const parsed = JSON.parse(text)
  if (!Array.isArray(parsed)) throw new Error('Client config must be an array.')
  return parsed
}

function sampleSnapshot(env, clients) {
  return {
    generatedAt: new Date().toISOString(),
    environment: env,
    sourceMode: 'sample',
    clients: clients.map((client) => client.name),
    kpis: [
      { key: 'active', label: 'Active orders', value: '18420', changeVsLastWeek: '+6.8%', direction: 'up', tone: 'neutral', help: 'Sample KPI' },
      { key: 'dt', label: 'Delivery time', value: '3.7 d', changeVsLastWeek: '+0.4 d', direction: 'up', tone: 'bad', help: 'Sample KPI' },
    ],
    clientMetrics: clients.map((client, index) => ({
      clientKey: client.key,
      clientName: client.name,
      activeOrders: 1500 + index * 2200,
      deliveryTimeDays: 3.1 + index * 0.4,
      firstAttemptDays: 2.1 + index * 0.3,
      noAttempt2d: 70 + index * 25,
      staleStatusOrders: 45 + index * 11,
      returns: 18 + index * 9,
      failed: 7 + index * 5,
      oldTails: 130 + index * 70,
      riskLevel: index === 0 ? 'high' : 'medium',
    })),
    cityMetrics: [],
    alerts: [
      {
        title: 'Sample snapshot only',
        scope: 'pipeline',
        severity: 'low',
        detail: 'Replace sample mode with real Shipox and Mongo collection logic.',
      },
    ],
    weeklyTrend: [],
    notes: [
      'This file is generated by the starter ETL.',
      'Real Shipox and Mongo wiring is the next implementation step.',
    ],
  }
}

async function main() {
  const options = parseArgs(process.argv.slice(2))
  if (options.help) {
    printHelp()
    return
  }

  const clients = await loadClients(path.resolve(ROOT, options.config))
  const outputFile =
    options.out ||
    path.join(ROOT, 'artifacts', options.env.toLowerCase(), 'latest-snapshot.json')

  await fs.mkdir(path.dirname(outputFile), { recursive: true })

  const snapshot = sampleSnapshot(options.env.toLowerCase(), clients)
  await fs.writeFile(outputFile, `${JSON.stringify(snapshot, null, 2)}\n`, 'utf8')

  console.log(
    JSON.stringify(
      {
        ok: true,
        env: options.env,
        sample: true,
        clients: clients.length,
        out: outputFile,
      },
      null,
      2,
    ),
  )
}

main().catch((error) => {
  console.error(error?.stack || error?.message || String(error))
  process.exit(1)
})
